default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: glima
  password: 102030
  host: localhost
  port: 5432
development:
  <<: *default
  database: microblog_development
test:
  <<: *default
  database: microblog_test
production:
  <<: *default
  database: microblog_production
  username: microblog
  password: <%= ENV['MICROBLOG_DATABASE_PASSWORD'] %>
